language: python
python:
- "2.7"
- "3.4"
install:
- pip install tox
before_script:
- psql -U postgres -c "CREATE ROLE history_user2 WITH CREATEUSER CREATEDB LOGIN PASSWORD 'pass';"
- psql -U postgres -c 'CREATE DATABASE test_history_db WITH OWNER history_user2;'
script:
- tox
